#
# This file has been automatically generated by the WICED 20719-B1 Designer.
#

APP_SRC = BLE_CO2_SensNet.c
APP_SRC += BLE_CO2_SensNet_db.c
APP_SRC += wiced_bt_cfg.c

########################################################################
# Component(s) needed
########################################################################
$(NAME)_COMPONENTS := spp_lib.a

APP_SRC += ../_Libraries/DHT.c
APP_SRC += ../_Libraries/PASCO2.c
APP_SRC += ../_Libraries/DPS368.c
APP_SRC += ../_Libraries/SHTC3.c
APP_SRC += ../_Libraries/BLE_CO2_CMD.c

########################################################################
# C flags
########################################################################
# If defined, HCI traces are sent over transport/WICED HCI interface
C_FLAGS += -DHCI_TRACE_OVER_TRANSPORT

########################################################################
################ DO NOT MODIFY FILE BELOW THIS LINE ####################
########################################################################
C_FLAGS += -DSMUX_CHIP=$(CHIP)
APP_SRC += BLE_CO2_SensNet_pin_config.c