/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_XENSIV_MEASUREMENT                                   0x9f, 0x63, 0x27, 0xc0, 0xea, 0x28, 0x4f, 0x06, 0xaf, 0xf7, 0x5d, 0x29, 0xda, 0xda, 0x13, 0x2a
#define __UUID_XENSIV_MEASUREMENT_CO2_DATA                          0x84, 0xc4, 0x19, 0x47, 0x68, 0x84, 0x46, 0x38, 0xa8, 0xec, 0xb4, 0x93, 0x63, 0x1e, 0xf3, 0x4e
#define __UUID_XENSIV_MEASUREMENT_PRESS_DATA                        0x3b, 0xd3, 0xa9, 0x97, 0x52, 0xab, 0x4d, 0xa4, 0xab, 0x1f, 0x95, 0x07, 0x0c, 0x4b, 0x4f, 0x0b
#define __UUID_XENSIV_MEASUREMENT_TEMP_DATA                         0xe4, 0x3c, 0x4a, 0xdb, 0x2a, 0xdc, 0x41, 0x8e, 0xab, 0xf0, 0x43, 0x8c, 0xaf, 0x30, 0xb3, 0x7e
#define __UUID_XENSIV_MEASUREMENT_HUM_DATA                          0x1f, 0x9a, 0x9c, 0x7e, 0x5a, 0x5c, 0x43, 0x47, 0xb6, 0x44, 0x2f, 0x11, 0x49, 0xa4, 0x1d, 0x42
#define __UUID_XENSIV_CONFIG                                        0xdd, 0x21, 0x91, 0x31, 0xf0, 0x2d, 0x4d, 0x4d, 0x9b, 0x26, 0x2c, 0xf7, 0x8a, 0x45, 0x19, 0x21
#define __UUID_XENSIV_CONFIG_SAMPLE_RATE                            0x1f, 0x06, 0x6d, 0x49, 0xfe, 0x10, 0x4f, 0x10, 0x8d, 0x7c, 0xba, 0x49, 0xc6, 0xe6, 0x20, 0x84
#define __UUID_XENSIV_CONFIG_ALARM_THRESHOLD                        0x09, 0x34, 0xf2, 0x76, 0x4f, 0x00, 0x42, 0x42, 0x86, 0xde, 0xba, 0x85, 0x99, 0x7e, 0xfb, 0x4f
#define __UUID_XENSIV_CONFIG_OFFSET_COMPENSATION                    0xa1, 0xbf, 0xd9, 0x98, 0x0f, 0xda, 0x47, 0x1b, 0xb2, 0xcf, 0x3d, 0xa9, 0x94, 0xfe, 0x8a, 0x6f
#define __UUID_XENSIV_CONFIG_ENABLE_CALIBRATION                     0x5c, 0x42, 0x39, 0x28, 0xf8, 0x5a, 0x4d, 0x9c, 0x96, 0xac, 0xf3, 0x07, 0x10, 0x05, 0x4d, 0xe6

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                                      0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                                         0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME                             0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE                       0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE                              0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE                        0x0018

// ***** Primary Service 'XENSIV_Measurement'
#define HDLS_XENSIV_MEASUREMENT                                     0x0028
// ----- Characteristic 'CO2_Data'
#define HDLC_XENSIV_MEASUREMENT_CO2_DATA                            0x0029
#define HDLC_XENSIV_MEASUREMENT_CO2_DATA_VALUE                      0x002A
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_MEASUREMENT_CO2_DATA_USER_DESCRIPTION           0x002B
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_MEASUREMENT_CO2_DATA_CLIENT_CONFIGURATION       0x002C
// ----- Characteristic 'Press_Data'
#define HDLC_XENSIV_MEASUREMENT_PRESS_DATA                          0x002D
#define HDLC_XENSIV_MEASUREMENT_PRESS_DATA_VALUE                    0x002E
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_MEASUREMENT_PRESS_DATA_USER_DESCRIPTION         0x002F
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_MEASUREMENT_PRESS_DATA_CLIENT_CONFIGURATION     0x0030
// ----- Characteristic 'Temp_Data'
#define HDLC_XENSIV_MEASUREMENT_TEMP_DATA                           0x0031
#define HDLC_XENSIV_MEASUREMENT_TEMP_DATA_VALUE                     0x0032
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_MEASUREMENT_TEMP_DATA_USER_DESCRIPTION          0x0033
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_MEASUREMENT_TEMP_DATA_CLIENT_CONFIGURATION      0x0034
// ----- Characteristic 'Hum_Data'
#define HDLC_XENSIV_MEASUREMENT_HUM_DATA                            0x0035
#define HDLC_XENSIV_MEASUREMENT_HUM_DATA_VALUE                      0x0036
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_MEASUREMENT_HUM_DATA_USER_DESCRIPTION           0x0037
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_MEASUREMENT_HUM_DATA_CLIENT_CONFIGURATION       0x0038

// ***** Primary Service 'XENSIV_Config'
#define HDLS_XENSIV_CONFIG                                          0x0040
// ----- Characteristic 'Sample_Rate'
#define HDLC_XENSIV_CONFIG_SAMPLE_RATE                              0x0041
#define HDLC_XENSIV_CONFIG_SAMPLE_RATE_VALUE                        0x0042
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_CONFIG_SAMPLE_RATE_USER_DESCRIPTION             0x0043
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_CONFIG_SAMPLE_RATE_CLIENT_CONFIGURATION         0x0044
// ----- Characteristic 'Alarm_Threshold'
#define HDLC_XENSIV_CONFIG_ALARM_THRESHOLD                          0x0045
#define HDLC_XENSIV_CONFIG_ALARM_THRESHOLD_VALUE                    0x0046
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_CONFIG_ALARM_THRESHOLD_USER_DESCRIPTION         0x0047
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_CONFIG_ALARM_THRESHOLD_CLIENT_CONFIGURATION     0x0048
// ----- Characteristic 'Offset_Compensation'
#define HDLC_XENSIV_CONFIG_OFFSET_COMPENSATION                      0x0049
#define HDLC_XENSIV_CONFIG_OFFSET_COMPENSATION_VALUE                0x004A
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_CONFIG_OFFSET_COMPENSATION_USER_DESCRIPTION     0x004B
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_CONFIG_OFFSET_COMPENSATION_CLIENT_CONFIGURATION 0x004C
// ----- Characteristic 'Enable_Calibration'
#define HDLC_XENSIV_CONFIG_ENABLE_CALIBRATION                       0x004D
#define HDLC_XENSIV_CONFIG_ENABLE_CALIBRATION_VALUE                 0x004E
// ===== Descriptor 'User Description'
#define HDLD_XENSIV_CONFIG_ENABLE_CALIBRATION_USER_DESCRIPTION      0x004F
// ===== Descriptor 'Client Configuration'
#define HDLD_XENSIV_CONFIG_ENABLE_CALIBRATION_CLIENT_CONFIGURATION  0x0050

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table ble_co2_sensnet_gatt_db_ext_attr_tbl[];
extern const uint16_t ble_co2_sensnet_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
